In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [34]:
from sklearn.datasets import load_digits
digits = load_digits()

In [13]:
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [14]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [15]:
tr = RandomForestClassifier()
tr.fit(x_train,y_train)
tr.score(x_test,y_test)

0.9703703703703703

In [20]:
sv = SVC(max_iter=90)
sv.fit(x_train,y_train)
sv.score(x_test,y_test)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=90).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(


0.9907407407407407

In [22]:
from sklearn.model_selection import KFold

In [27]:
kf = KFold(n_splits = 3)

In [28]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [31]:
from sklearn.model_selection import StratifiedKFold
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [42]:
kf = StratifiedKFold(n_splits = 3)

In [48]:
svc_l = []
rf_l = []
lr_l = []
for train_index,test_index in kf.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    lr_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    rf_l.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))
    svc_l.append(get_score(SVC(max_iter=10),x_train,x_test,y_train,y_test))
    
    

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    http

In [49]:
print("Logistic :",lr_l)

Logistic : [0.9215358931552587, 0.9415692821368948, 0.9165275459098498]


In [50]:
print("RandomForest :",rf_l)

RandomForest : [0.9248747913188647, 0.9532554257095158, 0.9265442404006677]


In [51]:
print("SVC : ",svc_l)

SVC :  [0.9515859766277128, 0.9649415692821369, 0.9549248747913188]


In [47]:
print(np.mean(lr_l))

0.9265442404006677


In [52]:
print(np.mean(rf_l))

0.9348914858096827


In [53]:
print(np.mean(svc_l))

0.9571508069003896


In [55]:
from sklearn.model_selection import cross_val_score

In [60]:
np.mean(cross_val_score(LogisticRegression(),digits.data,digits.target))

C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

0.9137650882079852

In [61]:
np.mean(cross_val_score(SVC(),digits.data,digits.target))

0.9632838130609718

In [62]:
np.mean(cross_val_score(RandomForestClassifier(),digits.data,digits.target))

0.9404766326214794